== copyright-statement
=== {blank}
{% if unpublished %}
*Copyright © {{ docyear }} International Electrotechnical Commission, IEC.*
All rights reserved. It is permitted to download this electronic file, to make a copy and to
print out the content for the sole purpose of preparing National Committee positions. You
may not copy or "mirror" the file or printed version of the document, or any part of it,
for any other purpose without permission in writing from IEC.
{% else %}
[[boilerplate-year]]
Copyright © {{ docyear }} {{ agency }}, Geneva, Switzerland

[[boilerplate-message]]
All rights reserved. Unless otherwise specified, no part of this publication may be reproduced or utilized in any form
or by any means, electronic or mechanical, including photocopying and microfilm, without permission in writing from
either IEC or IEC's member National Committee in the country of the requester. If you have any questions about
{{ agency }} copyright or have an enquiry about obtaining additional rights to this publication, please contact the address
below or your local IEC member National Committee for further information.

[[boilerplate-name]]
IEC Central Office

[[boilerplate-address]]
[align=left]
3, rue de Varembé +
CH-1211 Geneva 20 +
Switzerland +
Tel.:&#xa0;+41 22 919 02 11 +
link:mailto:info@iec.ch[info@iec.ch] +
link:https://www.iec.ch[www.iec.ch]
{% endif %}

== legal-statement
=== {blank}

[type="arabic"]
. The International Electrotechnical Commission (IEC) is a worldwide organization for standardization comprising all national electrotechnical committees (IEC National Committees). The object of IEC is to promote international co-operation on all questions concerning standardization in the electrical and electronic fields. To this end and in addition to other activities, IEC publishes International Standards, Technical Specifications, Technical Reports, Publicly Available Specifications (PAS) and Guides (hereafter referred to as “IEC Publication(s)”). Their preparation is entrusted to technical committees; any IEC National Committee interested in the subject dealt with may participate in this preparatory work. International, governmental and non-governmental organizations liaising with the IEC also participate in this preparation. IEC collaborates closely with the International Organization for Standardization (ISO) in accordance with conditions determined by agreement between the two organizations.
. The formal decisions or agreements of IEC on technical matters express, as nearly as possible, an international consensus of opinion on the relevant subjects since each technical committee has representation from all interested IEC National Committees.
. IEC Publications have the form of recommendations for international use and are accepted by IEC National Committees in that sense. While all reasonable efforts are made to ensure that the technical content of IEC Publications is accurate, IEC cannot be held responsible for the way in which they are used or for any misinterpretation by any end user.
. In order to promote international uniformity, IEC National Committees undertake to apply IEC Publications transparently to the maximum extent possible in their national and regional publications. Any divergence between any IEC Publication and the corresponding national or regional publication shall be clearly indicated in the latter.
. IEC itself does not provide any attestation of conformity. Independent certification bodies provide conformity assessment services and, in some areas, access to IEC marks of conformity. IEC is not responsible for any services carried out by independent certification bodies.
. All users should ensure that they have the latest edition of this publication.
. No liability shall attach to IEC or its directors, employees, servants or agents including individual experts and members of its technical committees and IEC National Committees for any personal injury, property damage or other damage of any nature whatsoever, whether direct or indirect, or for costs (including legal fees) and expenses arising out of the publication, use of, or reliance upon, this IEC Publication or any other IEC Publications.
. Attention is drawn to the Normative references cited in this publication. Use of the referenced publications is indispensable for the correct application of this publication.
. Attention is drawn to the possibility that some of the elements of this IEC Publication may be the subject of patent rights. IEC shall not be held responsible for identifying any or all such patent rights.

{% if unpublished %}
== license-statement
=== {blank}
{% if stage_int < 50 %}
This document is still under study and subject to change. It should not be used for reference purposes.
until published as such.
{% endif %}

{% if stage_int >= 50 %}
This document is a draft distributed for approval. It may not be referred to as an International Standard
until published as such.
{% endif %}

{% if stage_int >= 50 %}
In addition to their evaluation as being acceptable for industrial, technological, commercial and user
purposes, Final Draft International Standards may on occasion have to be considered in the light of their
potential to become standards to which reference may be made in national regulations.
{% endif %}

Recipients of this document are invited to submit, with their comments, notification of any relevant
patent rights of which they are aware and to provide supporting documentation.
{% endif %}

== feedback-statement
{% if unpublished %}
[[boilerplate-cenelec-attention]]
=== Attention IEC-CENELEC parallel voting

The attention of IEC National Committees, members of CENELEC, is drawn to the fact that this
{% if stage_int >= 30 and stage_int < 40 %}Committee Draft{% endif %}
{% if stage_int >= 40 and stage_int < 50 %}Committee Draft For Vote{% endif %}
{% if stage_int >= 50 and stage_int < 60 %}Final Draft International Standard{% endif %}
({{ stageabbr }})
is submitted for parallel voting.

The CENELEC members are invited to vote through the CENELEC voting system.
{% else %}
=== About the IEC
The International Electrotechnical Commission (IEC) is the leading global organization that prepares and publishes International Standards for all electrical, electronic and related technologies.

=== About IEC publications
The technical content of IEC publications is kept under constant review by the IEC. Please make sure that you have the latest edition, a corrigenda or an amendment might have been published.

=== {blank}
==== IEC Catalogue - https://webstore.iec.ch/catalogue:[webstore.iec.ch/catalogue]

The stand-alone application for consulting the entire bibliographical information on IEC International Standards, Technical Specifications, Technical Reports and other documents. Available for PC, Mac OS, Android Tablets and iPad.

==== IEC publications search - https://www.iec.ch/searchpub:[www.iec.ch/searchpub]
The advanced search enables to find IEC publications by a variety of criteria (reference number, text, technical committee,...). It also gives information on projects, replaced and withdrawn publications.

==== IEC Just Published - https://webstore.iec.ch/justpublished:[webstore.iec.ch/justpublished]
Stay up to date on all new IEC publications. Just Published details all new publications released. Available online and also once a month by email.

==== Electropedia - http://www.electropedia.org:[www.electropedia.org]
The world's leading online dictionary of electronic and electrical terms containing more than 30 000 terms and definitions in English and French, with equivalent terms in 14 additional languages. Also known as the International Electrotechnical Vocabulary (IEV) online.

==== IEC Glossary - http://std.iec.ch/glossary:[std.iec.ch/glossary]
More than 55 000 electrotechnical terminology entries in English and French extracted from the Terms and Definitions clause of IEC publications issued since 2002. Some entries have been collected from earlier publications of IEC TC 37, 77, 86 and CISPR.

==== IEC Customer Service Centre - https://webstore.iec.ch/csc:[webstore.iec.ch/csc]
If you wish to give us your feedback on this publication or need further assistance, please contact the Customer Service Centre: link:mailto:csc@iec.ch[csc@iec.ch].
{% endif %}

