== copyright-statement
=== {blank} 
{% if unpublished %}
*Copyright © {{ docyear }} Commission électrotechnique internationale, IEC.*
Tous droits réservés. Il est permis de télécharger ce fichier électronique, d'en faire une copie et de
imprimer le contenu dans le seul but de préparer les positions du Comité national. Toi
ne peut pas copier ou « refléter » le fichier ou la version imprimée du document, ou toute partie de celui-ci,
à toute autre fin sans autorisation écrite de la IEC.
{% else %}
[[boilerplate-year]]
Copyright © {{ docyear }} {{ agency }}, Genève, Suisse


[[boilerplate-message]]
Droits de reproduction réservés. Sauf indication contraire, aucune partie de cette publication ne peut être reproduite
ni utilisée sous quelque forme que ce soit et par aucun procédé, électronique ou mécanique, y compris la photocopie
et les microfilms, sans l'accord écrit de l'IEC ou du Comité national de l'IEC du pays du demandeur. Si vous avez des
questions sur le copyright de l'{{ agency }} ou si vous désirez obtenir des droits supplémentaires sur cette publication, utilisez
les coordonnées ci-après ou contactez le Comité national de l'IEC de votre pays de résidence.

[[boilerplate-name]]
IEC Central Office 

[[boilerplate-address]]
[align=left]
3, rue de Varembé +
CH-1211 Geneva 20 +
Switzerland +
Tel.:&#xa0;+41 22 919 02 11 + 
link:mailto:info@iec.ch[info@iec.ch] +
link:https://www.iec.ch[www.iec.ch]
{% endif %}

== legal-statement
=== {blank}

[arabic]
. La Commission Electrotechnique Internationale (IEC) est une organisation mondiale de normalisation composée de l'ensemble des comités électrotechniques nationaux (Comités nationaux de l’IEC). L’IEC a pour objet de favoriser la coopération internationale pour toutes les questions de normalisation dans les domaines de l'électricité et de l'électronique. A cet effet, l’IEC – entre autres activités – publie des Normes internationales, des Spécifications techniques, des Rapports techniques, des Spécifications accessibles au public (PAS) et des Guides (ci-après dénommés "Publication(s) de l’IEC"). Leur élaboration est confiée à des comités d'études, aux travaux desquels tout Comité national intéressé par le sujet traité peut participer. Les organisations internationales, gouvernementales et non gouvernementales, en liaison avec l’IEC, participent également aux travaux. L’IEC collabore étroitement avec l'Organisation Internationale de Normalisation (ISO), selon des conditions fixées par accord entre les deux organisations.
. Les décisions ou accords officiels de l’IEC concernant les questions techniques représentent, dans la mesure du possible, un accord international sur les sujets étudiés, étant donné que les Comités nationaux de l’IEC intéressés sont représentés dans chaque comité d’études.
. Les Publications de l’IEC se présentent sous la forme de recommandations internationales et sont agréées comme telles par les Comités nationaux de l’IEC. Tous les efforts raisonnables sont entrepris afin que l’IEC s'assure de l'exactitude du contenu technique de ses publications; l’IEC ne peut pas être tenue responsable de l'éventuelle mauvaise utilisation ou interprétation qui en est faite par un quelconque utilisateur final.
. Dans le but d'encourager l'uniformité internationale, les Comités nationaux de l’IEC s'engagent, dans toute la mesure possible, à appliquer de façon transparente les Publications de l’IEC dans leurs publications nationales et régionales. Toutes divergences entre toutes Publications de l’IEC et toutes publications nationales ou régionales correspondantes doivent être indiquées en termes clairs dans ces dernières.
. L’IEC elle-même ne fournit aucune attestation de conformité. Des organismes de certification indépendants fournissent des services d'évaluation de conformité et, dans certains secteurs, accèdent aux marques de conformité de l’IEC. L’IEC n'est responsable d'aucun des services effectués par les organismes de certification indépendants.
. Tous les utilisateurs doivent s'assurer qu'ils sont en possession de la dernière édition de cette publication.
. Aucune responsabilité ne doit être imputée à l’IEC, à ses administrateurs, employés, auxiliaires ou mandataires, y compris ses experts particuliers et les membres de ses comités d'études et des Comités nationaux de l’IEC, pour tout préjudice causé en cas de dommages corporels et matériels, ou de tout autre dommage de quelque nature que ce soit, directe ou indirecte, ou pour supporter les coûts (y compris les frais de justice) et les dépenses découlant de la publication ou de l'utilisation de cette Publication de l’IEC ou de toute autre Publication de l’IEC, ou au crédit qui lui est accordé.
. L'attention est attirée sur les références normatives citées dans cette publication. L'utilisation de publications référencées est obligatoire pour une application correcte de la présente publication.
. L’attention est attirée sur le fait que certains des éléments de la présente Publication de l’IEC peuvent faire l’objet de droits de brevet. L’IEC ne saurait être tenue pour responsable de ne pas avoir identifié de tels droits de brevets et de ne pas avoir signalé leur existence.

{% if unpublished %}
== license-statement
=== {blank}
{% if stage_int < 50 %}
Ce document est encore à l'étude et susceptible d'être modifié. Il ne doit pas être utilisé à des fins de référence.
jusqu'à ce qu'il soit publié comme tel.
{% endif %}

{% if stage_int >= 50 %}
Ce document est une ébauche distribuée pour approbation. Il ne peut pas être qualifié de Norme internationale
jusqu'à ce qu'il soit publié comme tel.
{% endif %}

{% if stage_int >= 50 %} 
En plus de leur évaluation comme étant acceptable pour les industriels, technologiques, commerciaux et utilisateurs
À ces fins, les projets finaux de Normes internationales peuvent parfois devoir être examinés à la lumière de leur
susceptibles de devenir des normes auxquelles il pourra être fait référence dans les réglementations nationales.
{% endif %}

Les destinataires de ce document sont invités à soumettre, avec leurs commentaires, notification de tout
droits de brevet dont ils ont connaissance et de fournir les pièces justificatives.
{% endif %}

== feedback-statement
{% if unpublished %}
[[boilerplate-cenelec-attention]]
=== Attention vote parallèle IEC-CENELEC

L'attention des Comités Nationaux de la CEI, membres du CENELEC, est attirée sur le fait que ce
{% if stage_int >= 30 and stage_int < 40 %}Brouillon du comité{% endif %}
{% if stage_int >= 40 and stage_int < 50 %}Brouillon du comité pour vote{% endif %}
{% if stage_int >= 50 and stage_int < 60 %}Brouillon final de norme internationale{% endif %}
({{ stageabbr }})
est soumis au vote parallèle.

Les membres du CENELEC sont invités à voter via le système de vote du CENELEC.

{% else %}
=== A propos de l'IEC
La Commission Electrotechnique Internationale (IEC) est la première organisation mondiale qui élabore et publie des Normes internationales pour tout ce qui a trait à l'électricité, à l'électronique et aux technologies apparentées.

=== A propos des publications IEC
Le contenu technique des publications IEC est constamment revu. Veuillez vous assurer que vous possédez l’édition la plus récente, un corrigendum ou amendement peut avoir été publié.

=== {blank}
==== Catalogue IEC - https://webstore.iec.ch/catalogue:[webstore.iec.ch/catalogue]
Application autonome pour consulter tous les renseignements bibliographiques sur les Normes internationales, Spécifications techniques, Rapports techniques et autres documents de l'IEC. Disponible pour PC, Mac OS, tablettes Android et iPad.

==== Recherche de publications IEC - https://www.iec.ch/searchpub:[www.iec.ch/searchpub]
La recherche avancée permet de trouver des publications IEC en utilisant différents critères (numéro de référence, texte, comité d’études,...). Elle donne aussi des informations sur les projets et les publications remplacées ou retirées.

==== IEC Just Published - https://webstore.iec.ch/justpublished:[webstore.iec.ch/justpublished]
Restez informé sur les nouvelles publications IEC. Just Published détaille les nouvelles publications parues. Disponible en ligne et aussi une fois par mois par email.

==== Electropedia - http://www.electropedia.org:[www.electropedia.org]
Le premier dictionnaire en ligne de termes électroniques et électriques. Il contient plus de 30 000 termes et définitions en anglais et en français, ainsi que les termes équivalents dans 14 langues additionnelles. Egalement appelé Vocabulaire Electrotechnique International (IEV) en ligne.

==== Glossaire IEC - http://std.iec.ch/glossary:[std.iec.ch/glossary]
Plus de 55 000 entrées terminologiques électrotechniques, en anglais et en français, extraites des articles Termes et Définitions des publications IEC parues depuis 2002. Plus certaines entrées antérieures extraites des publications des CE 37, 77, 86 et CISPR de l'IEC.

==== Service Clients - https://webstore.iec.ch/csc:[webstore.iec.ch/csc]
Si vous désirez nous donner des commentaires sur cette publication ou si vous avez des questions contactez-nous: link:mailto:csc@iec.ch[csc@iec.ch].
{% endif %}

